server:
  port: 8082

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@120.78.238.174:1521:zmbx
    username: yike
    password: 6694030
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mybatis/*Mapper.xml
  typeAliasesPackage: com.zhongmin.**.domain

logging.level.com.zhongmin.dao: debug
